package org.teche.merv.client.report.html;

/**
 * Share / Download chrome for local suite HTML ({@code MervCucumberHandler.buildLiveHtmlReportContent}).
 * Mirrors merv-client-js suite template behaviour (HTTP-only; hidden on {@code file://}).
 */
public final class MervSuiteShareDownloadHtml {

    private MervSuiteShareDownloadHtml() {
    }

    public static String css() {
        return ""
                + ".suite-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;flex-wrap:wrap;"
                + "border-bottom:4px solid #c20000;padding-bottom:12px;margin-bottom:10px;}"
                + "h1#suite-title{border-bottom:none;padding-bottom:0;margin:0;flex:1;min-width:0;font-size:26px;}"
                + ".suite-heading-actions{display:flex;align-items:center;gap:8px;flex-shrink:0;margin-top:4px;}"
                + ".share-btn,.download-btn{appearance:none;border:1px solid #c20000;background:#fff;color:#c20000;"
                + "font:inherit;font-size:13px;font-weight:700;padding:6px 12px;border-radius:8px;cursor:pointer;}"
                + ".share-btn:hover{background:#fdeaea;}"
                + ".download-btn{background:linear-gradient(180deg,#e90101,#c20000);color:#fff;border-color:#c20000;}"
                + ".download-btn:hover{filter:brightness(1.05);}"
                + ".download-btn:disabled{opacity:.65;cursor:wait;filter:none;}"
                + ".merv-share-modal,.merv-download-toast{display:none;position:fixed;inset:0;z-index:10050;"
                + "align-items:center;justify-content:center;padding:20px;}"
                + ".merv-share-modal.open,.merv-download-toast.open{display:flex;}"
                + ".merv-share-backdrop,.merv-download-toast-backdrop{position:absolute;inset:0;background:rgba(17,24,39,.45);}"
                + ".merv-share-panel,.merv-download-toast-panel{position:relative;z-index:1;width:min(560px,100%);"
                + "max-height:min(90vh,720px);overflow:auto;background:#fff;border-radius:14px;border:1px solid #e8eaed;"
                + "box-shadow:0 16px 48px rgba(0,0,0,.22);padding:20px 22px 18px;}"
                + ".merv-download-toast-panel{width:min(420px,100%);text-align:center;}"
                + ".merv-share-panel h2,.merv-download-toast-panel h2{margin:0 0 6px;font-size:18px;color:#1a1a1a;}"
                + ".merv-share-panel .share-sub{margin:0 0 14px;font-size:13px;color:#6b7280;}"
                + ".merv-share-row{display:flex;gap:8px;margin-bottom:14px;}"
                + ".merv-share-row input{flex:1;min-width:0;border:1px solid #d1d5db;border-radius:8px;padding:10px 12px;"
                + "font-size:13px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}"
                + ".merv-share-copy,.merv-download-toast-ok{appearance:none;border:none;border-radius:8px;padding:0 14px;"
                + "background:linear-gradient(180deg,#e90101,#c20000);color:#fff;font-weight:700;font-size:13px;cursor:pointer;}"
                + ".merv-download-toast-ok{padding:8px 18px;}"
                + ".merv-share-status{min-height:18px;margin:-6px 0 12px;font-size:12px;color:#1b5e20;font-weight:600;}"
                + ".merv-share-warn{margin:0 0 12px;padding:10px 12px;border-radius:10px;background:#fff7ed;"
                + "border:1px solid #fed7aa;color:#9a3412;font-size:13px;line-height:1.45;}"
                + ".merv-share-notes{margin:0;padding-left:18px;font-size:13px;line-height:1.55;color:#374151;}"
                + ".merv-share-notes li{margin:0 0 10px;}"
                + ".merv-share-notes code{font-size:12px;background:#f3f4f6;padding:1px 5px;border-radius:4px;}"
                + ".merv-share-close{position:absolute;top:12px;right:12px;border:none;background:transparent;"
                + "font-size:22px;line-height:1;color:#6b7280;cursor:pointer;}"
                + ".merv-download-toast-panel .size-line{margin:0 0 14px;font-size:15px;color:#374151;}"
                + ".merv-download-toast-panel .size-line strong{color:#c20000;}"
                + ".merv-download-toast-panel .detail{margin:0 0 16px;font-size:13px;color:#6b7280;line-height:1.45;}";
    }

    /** Markup after Local Dashboard link row — suite heading actions + modals (placed after h1 replacement). */
    public static String headingActionsMarkup() {
        return "<div class='suite-heading'>"
                + "<h1 id='suite-title'>Merv Live Runtime Report <span id='run-state' class='status-pill'>RUNNING</span></h1>"
                + "<div class='suite-heading-actions' id='suite-heading-actions'>"
                + "<button type='button' class='share-btn' id='share-report-btn' title='Share this report link'>Share</button>"
                + "<button type='button' class='download-btn' id='download-report-btn' "
                + "title='Download emailable report and offline zip'>Download</button>"
                + "</div></div>";
    }

    public static String modalsMarkup() {
        return ""
                + "<div class='merv-share-modal' id='merv-share-modal' aria-hidden='true'>"
                + "<div class='merv-share-backdrop' id='merv-share-backdrop'></div>"
                + "<div class='merv-share-panel' role='dialog' aria-labelledby='merv-share-title'>"
                + "<button type='button' class='merv-share-close' id='merv-share-close' aria-label='Close'>×</button>"
                + "<h2 id='merv-share-title'>Share this report</h2>"
                + "<p class='share-sub'>Copy this link and send it to someone on your network.</p>"
                + "<div class='merv-share-row'>"
                + "<input id='merv-share-link' type='text' readonly spellcheck='false'/>"
                + "<button type='button' class='merv-share-copy' id='merv-share-copy'>Copy</button>"
                + "</div>"
                + "<div class='merv-share-status' id='merv-share-status' aria-live='polite'></div>"
                + "<div class='merv-share-warn' id='merv-share-warn' hidden></div>"
                + "<ol class='merv-share-notes'>"
                + "<li>The port must be reachable and <strong>not blocked by a firewall</strong>. "
                + "The person you share with must be on the <strong>same network</strong>.</li>"
                + "<li>The report is visible <strong>only while the MERV report server is running</strong> "
                + "(<code>npx merv show-report</code> or Java <code>MervLocalReportServer</code>). "
                + "When you stop the server, the link stops working.</li>"
                + "<li>If the port is blocked, use an allowed port (usually <strong>80</strong> or <strong>443</strong>), "
                + "e.g. <code>npx merv show-report --host 0.0.0.0 --port 80</code>, or open the port in firewall settings. "
                + "Use <code>--host 0.0.0.0</code> so LAN clients can connect.</li>"
                + "<li>If you still cannot share, use <strong>Merv-Server</strong> "
                + "(<code>merv.local=false</code> with your MERV API key).</li>"
                + "</ol></div></div>"
                + "<div class='merv-download-toast' id='merv-download-toast' aria-hidden='true'>"
                + "<div class='merv-download-toast-backdrop' id='merv-download-toast-backdrop'></div>"
                + "<div class='merv-download-toast-panel' role='dialog'>"
                + "<h2>Zip folder downloaded</h2>"
                + "<p class='size-line'>Size — <strong id='merv-download-toast-size'>—</strong></p>"
                + "<p class='detail' id='merv-download-toast-detail'>"
                + "Emailable report and offline zip (with <code>index.html</code>) were saved.</p>"
                + "<button type='button' class='merv-download-toast-ok' id='merv-download-toast-ok'>OK</button>"
                + "</div></div>";
    }

    /** JS appended before closing script — uses existing {@code e()} / {@code detectReportFolderName} if present. */
    public static String initScript() {
        return ""
                + "(function hideOfflineShareDownload(){"
                + "if(location.protocol!=='file:')return;"
                + "var actions=document.getElementById('suite-heading-actions');if(actions)actions.hidden=true;"
                + "var share=document.getElementById('share-report-btn');var dl=document.getElementById('download-report-btn');"
                + "if(share)share.hidden=true;if(dl)dl.hidden=true;"
                + "document.querySelectorAll('a.local-dash,a.sidebar-local-label').forEach(function(el){"
                + "if(el.classList.contains('sidebar-local-label')){"
                + "var span=document.createElement('span');span.className='sidebar-local-label';span.textContent='Merv';"
                + "el.replaceWith(span);}else{el.remove();}});})();"
                + "(function initShareReport(){"
                + "var modal=document.getElementById('merv-share-modal');"
                + "var btn=document.getElementById('share-report-btn');"
                + "var closeBtn=document.getElementById('merv-share-close');"
                + "var backdrop=document.getElementById('merv-share-backdrop');"
                + "var linkInput=document.getElementById('merv-share-link');"
                + "var copyBtn=document.getElementById('merv-share-copy');"
                + "var statusEl=document.getElementById('merv-share-status');"
                + "var warnEl=document.getElementById('merv-share-warn');"
                + "if(!modal||!btn||!linkInput)return;"
                + "function setStatus(t){if(statusEl)statusEl.textContent=t||'';}"
                + "function setWarn(html){if(!warnEl)return;if(!html){warnEl.hidden=true;warnEl.innerHTML='';return;}"
                + "warnEl.hidden=false;warnEl.innerHTML=html;}"
                + "function buildShareUrl(info){var loc=window.location;if(loc.protocol==='file:')return loc.href;"
                + "var path=loc.pathname+loc.search+loc.hash;"
                + "var host=(info&&info.suggestedHost)||(info&&info.lanAddresses&&info.lanAddresses[0])||loc.hostname;"
                + "var port=(info&&info.port)||loc.port||'6174';"
                + "var portPart=(port==='80'&&loc.protocol==='http:')||(port==='443'&&loc.protocol==='https:')?'':(':'+port);"
                + "return loc.protocol+'//'+host+portPart+path;}"
                + "async function loadShareInfo(){try{var res=await fetch('/api/share-info',{cache:'no-store'});"
                + "if(!res.ok)return null;return await res.json();}catch(err){return null;}}"
                + "async function openModal(){setStatus('');var loc=window.location;"
                + "if(loc.protocol==='file:'){linkInput.value=loc.href;setWarn("
                + "'Start the report server so others can open it: <code>npx merv show-report --host 0.0.0.0</code>');"
                + "}else{var info=await loadShareInfo();linkInput.value=buildShareUrl(info);"
                + "if(info&&(info.localOnly||info.lanReachable===false)){setWarn('This server is bound to <code>'"
                + "+e(String(info.bindHost||'127.0.0.1'))+'</code> (local only). Restart with "
                + "<code>npx merv show-report --host 0.0.0.0 --port '+e(String(info.port||'6174'))+'</code>.');"
                + "}else if(!info){setWarn('Could not load LAN share details. Restart with "
                + "<code>npx merv show-report --host 0.0.0.0</code>.');}else{setWarn('');}}"
                + "modal.classList.add('open');modal.setAttribute('aria-hidden','false');"
                + "linkInput.focus();linkInput.select();}"
                + "function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');setStatus('');}"
                + "async function copyLink(){var text=linkInput.value;try{"
                + "if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text);}"
                + "else{linkInput.select();document.execCommand('copy');}setStatus('Link copied');}"
                + "catch(err){linkInput.select();setStatus('Press Ctrl/Cmd+C to copy');}}"
                + "btn.addEventListener('click',function(){void openModal();});"
                + "if(closeBtn)closeBtn.addEventListener('click',closeModal);"
                + "if(backdrop)backdrop.addEventListener('click',closeModal);"
                + "if(copyBtn)copyBtn.addEventListener('click',function(){void copyLink();});"
                + "document.addEventListener('keydown',function(ev){"
                + "if(ev.key==='Escape'&&modal.classList.contains('open'))closeModal();});})();"
                + "(function initDownloadReport(){"
                + "var btn=document.getElementById('download-report-btn');"
                + "var toast=document.getElementById('merv-download-toast');"
                + "var toastSize=document.getElementById('merv-download-toast-size');"
                + "var toastDetail=document.getElementById('merv-download-toast-detail');"
                + "var toastOk=document.getElementById('merv-download-toast-ok');"
                + "var toastBackdrop=document.getElementById('merv-download-toast-backdrop');"
                + "if(!btn)return;"
                + "function closeToast(){if(!toast)return;toast.classList.remove('open');"
                + "toast.setAttribute('aria-hidden','true');}"
                + "function openToast(sizeLabel,detail){if(toastSize)toastSize.textContent=sizeLabel||'—';"
                + "if(toastDetail&&detail)toastDetail.textContent=detail;"
                + "if(!toast)return;toast.classList.add('open');toast.setAttribute('aria-hidden','false');}"
                + "async function downloadBlob(url,filename){var res=await fetch(url,{cache:'no-store'});"
                + "if(!res.ok)throw new Error('Download failed ('+res.status+')');var blob=await res.blob();"
                + "var a=document.createElement('a');var obj=URL.createObjectURL(blob);a.href=obj;"
                + "a.download=filename||'download';document.body.appendChild(a);a.click();a.remove();"
                + "setTimeout(function(){URL.revokeObjectURL(obj);},1500);}"
                + "function detectFolder(){try{var p=String(window.location.pathname||'').replace(/\\\\/g,'/');"
                + "var parts=p.split('/').filter(Boolean);var htmlIdx=parts.lastIndexOf('html');"
                + "if(htmlIdx>0)return decodeURIComponent(parts[htmlIdx-1]);"
                + "if(parts.length>1)return decodeURIComponent(parts[parts.length-2]);}catch(err){}return '—';}"
                + "async function onDownload(){if(location.protocol==='file:'){"
                + "openToast('—','Open with npx merv show-report (or MervLocalReportServer) to download.');return;}"
                + "var folder=detectFolder();if(!folder||folder==='—'){openToast('—','Could not detect report folder.');return;}"
                + "var prev=btn.textContent;btn.disabled=true;btn.textContent='Preparing…';"
                + "try{var res=await fetch('/api/prepare-download?folder='+encodeURIComponent(folder),{cache:'no-store'});"
                + "var info=await res.json();if(!res.ok||!info||!info.ok){"
                + "throw new Error((info&&info.error)||'Prepare download failed');}"
                + "await downloadBlob(info.emailableUrl,info.emailableFileName||'emailable-report.html');"
                + "await downloadBlob(info.zipUrl,info.zipFileName||'merv-report-offline.zip');"
                + "openToast(info.zipSizeLabel||'—','Emailable report ('+(info.emailableSizeLabel||'—')"
                + "+') and offline zip were downloaded.');}"
                + "catch(err){openToast('—','Download failed: '+(err&&err.message?err.message:String(err))"
                + "+'. Start npx merv show-report or MervLocalReportServer.');}"
                + "finally{btn.disabled=false;btn.textContent=prev||'Download';}}"
                + "btn.addEventListener('click',function(){void onDownload();});"
                + "if(toastOk)toastOk.addEventListener('click',closeToast);"
                + "if(toastBackdrop)toastBackdrop.addEventListener('click',closeToast);"
                + "document.addEventListener('keydown',function(ev){"
                + "if(ev.key==='Escape'&&toast&&toast.classList.contains('open'))closeToast();});})();";
    }
}
